# frozen_string_literal: true

class V1::PredefinedParticipantSerializer < V1Serializer
  attributes :full_name, :first_name, :last_name, :email, :active, :email_autogenerated, :sms_notification, :email_notification

  attribute :phone do |object|
    object.phone.as_json(only: %i[iso prefix number confirmed])
  end

  %i[slug auto_invitation sms_invitation_sent_at email_invitation_sent_at health_clinic_id external_id].each do |attr|
    attribute attr do |object|
      object.predefined_user_parameter.send(attr)
    end
  end
end
