# frozen_string_literal: true

class V1::PredefinedParticipantSerializer < V1Serializer
  attributes :full_name, :first_name, :last_name, :email, :active, :email_autogenerated

  attribute :phone do |object|
    object.phone.as_json(only: %i[iso prefix number confirmed])
  end

  %i[slug auto_invitation sms_invitation_sent_at email_invitation_sent_at health_clinic_id external_id sms_notification email_notification].each do |attr|
    attribute attr do |object|
      object.predefined_user_parameter.send(attr)
    end
  end

  attribute :ra_session_completed do |object, params|
    params[:ra_user_sessions]&.dig(object.id)&.finished_at.present? || false
  end

  attribute :ra_session_finished_at do |object, params|
    params[:ra_user_sessions]&.dig(object.id)&.finished_at
  end

  attribute :ra_session_fulfilled_by_email do |object, params|
    params[:ra_user_sessions]&.dig(object.id)&.fulfilled_by&.email
  end
end
