# frozen_string_literal: true

require 'rails_helper'

RSpec.describe 'POST /v1/interventions/:intervention_id/predefined_participants/:id/sms_email_invitation', type: :request do
  let!(:intervention) { create(:intervention, :with_predefined_participants, user: researcher) }
  let(:researcher) { create(:user, :researcher, :confirmed) }
  let(:user) { intervention.predefined_users.first }
  let(:user_id) { user.id }
  let(:current_user) { researcher }
  let(:request) do
    post send_email_invitation_v1_intervention_predefined_participant_path(intervention_id: intervention.id, id: user_id),
         headers: current_user.create_new_auth_token
  end

  it 'return correct body' do
    request
    expect(json_response['email_invitation_sent_at']).to be_nil
  end

  context 'when user has assigned phone' do
    before do
      user.update(email_autogenerated: false)
    end

    it 'return correct status' do
      request
      expect(response).to have_http_status(:ok)
    end

    it 'return correct body' do
      request
      expect(json_response['email_invitation_sent_at']).to be_present
    end
  end

  context 'when id is wrong' do
    let(:user_id) { 'wrongId' }

    it 'return correct status' do
      request
      expect(response).to have_http_status(:not_found)
    end
  end

  it_behaves_like 'users without access'
end
