version: '3.8'

x-environment:
  &default-environment
  - RAILS_ENV=development

x-env_file:
  &default-env_file
  - './.env'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *default-environment
    env_file: *default-env_file
    depends_on:
      - cache
      - database
    stdin_open: true
    tty: true
    volumes:
      - .:/api
      - ./config/database.docker.yml:/api/config/database.yml
      - vol_api_bundle:/usr/local/bundle
      - vol_api_log:/api/log
      - vol_api_storage:/api/storage
      - vol_api_tmp:/api/tmp
    ports:
      - '3000:3000'
    command: >
      bash -c 'rm -f tmp/pids/server.pid
      && touch tmp/caching-dev.txt
      && bundle exec puma -C config/puma.rb'

  cache:
    image: redis:6.0.8-alpine
    command: 'redis-server'
    tmpfs:
      - /data
      - /run
      - /tmp

  database:
    image: postgres:13.0-alpine
    env_file: *default-env_file
    volumes:
      - vol_database:/var/lib/postgresql/data

  job_delay:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *default-environment
    env_file: *default-env_file
    depends_on:
      - cache
      - database
    stdin_open: true
    tty: true
    volumes:
      - .:/api
      - ./config/database.docker.yml:/api/config/database.yml
      - vol_api_bundle:/usr/local/bundle
      - vol_api_log:/api/log
      - vol_api_storage:/api/storage
      - vol_api_tmp:/api/tmp
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

volumes:
  vol_api_bundle:
  vol_api_log:
  vol_api_storage:
  vol_api_tmp:
  vol_database:
