version: '3.8'

x-environment:
  &default-environment
  - RAILS_ENV=development

x-env_file:
  &default-env_file
  - './.env'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *default-environment
    env_file: *default-env_file
    depends_on:
      - cache
      - database
    stdin_open: true
    tty: true
    volumes:
      - .:/api
      - vol_api_bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb'

  cache:
    image: redis:6.0.1
    command: 'redis-server'
    tmpfs:
      - /data
      - /run
      - /tmp

  database:
    image: postgres:12.2
    env_file: *default-env_file
    volumes:
      - vol_database:/var/lib/postgresql/data

  job_delay:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *default-environment
    env_file: *default-env_file
    depends_on:
      - cache
      - database
    stdin_open: true
    tty: true
    volumes:
      - .:/api
      - vol_api_bundle:/usr/local/bundle
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

volumes:
  vol_api_bundle:
  vol_database:
