version: '3.8'

x-environment:
  &default-environment
  - RAILS_ENV=development

x-env_file:
  &default-env_file
  - './.env'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    environment: *default-environment
    env_file: *default-env_file
    depends_on:
      - cache
      - database
    stdin_open: true
    tty: true
    volumes:
      - .:/api
    ports:
      - '3002:3000'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"

  cache:
    image: redis:5.0.6
    command: 'redis-server'
    tmpfs:
      - /data
      - /run
      - /tmp

  database:
    image: postgres:12.2
    env_file: *default-env_file
    volumes:
      - vol_database:/var/lib/postgresql/data

  job_delay:
    build:
      context: .
      dockerfile: Dockerfile-job_delay
    environment: *default-environment
    env_file: *default-env_file
    depends_on:
      - cache
      - database
    stdin_open: true
    tty: true
    volumes:
      - .:/api
    command: 'overmind start -f ./Procfile-job_delay OVERMIND_AUTO_RESTART=default,mailers'

volumes:
  vol_database:
