version: '3.8'

x-environment:
  &default-environment
  - RAILS_ENV=development

x-env_file:
  &default-env_file
  - './.env'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *default-environment
    env_file: *default-env_file
    depends_on:
      - cache
      - database
    stdin_open: true
    tty: true
    volumes:
      - .:/api
      - vol_api_bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb'

  cache:
    image: redis:6.0.4
    command: 'redis-server'
    tmpfs:
      - /data
      - /run
      - /tmp

  database:
    image: postgres:13
    env_file: *default-env_file
    volumes:
      - vol_database:/var/lib/postgresql/data

  database_data_visualisation:
    image: metabase/metabase
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    depends_on:
      - database
    volumes:
      - vol_database_data_visualisation:/metabase-data
    ports:
      - '3002:3000'

  database_ddl_inspect:
    image: ankane/pghero
    environment:
      - DATABASE_URL=postgres://postgres:7AU0lHRd5OglmKO@database:5432/cias_development
    depends_on:
      - database
    ports:
      - '3004:8080'

  job_delay:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *default-environment
    env_file: *default-env_file
    depends_on:
      - cache
      - database
    stdin_open: true
    tty: true
    volumes:
      - .:/api
      - vol_api_bundle:/usr/local/bundle
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

volumes:
  vol_api_bundle:
  vol_database:
  vol_database_data_visualisation:
