# frozen_string_literal: true

class V1::Intervention::PredefinedParticipants::SendEmailInvitation
  def initialize(user)
    @user = user
  end

  def self.call(user)
    new(user).call
  end

  def call
    raise ActiveRecord::ActiveRecordError, I18n.t('users.invite.predefined.not_active') unless user.active?
    return if user.email_autogenerated

    intervention = predefined_user_parameter.intervention
    InterventionMailer.with(locale: intervention.language_code).inform_to_an_email(intervention, user.email).deliver_now
    user.predefined_user_parameter.update!(email_invitation_sent_at: DateTime.now)
  end

  attr_accessor :user

  private

  def predefined_user_parameter
    @predefined_user_parameter ||= user.predefined_user_parameter
  end
end
