# frozen_string_literal: true

RSpec.describe V1::Intervention::PredefinedParticipants::CreateService do
  subject { described_class.call(intervention, params) }

  let!(:intervention) { create(:intervention) }
  let!(:health_clinic_id) { create(:health_clinic).id }
  let(:params) do
    {
      first_name: Faker::Name.first_name,
      last_name: Faker::Name.last_name,
      health_clinic_id: health_clinic_id,
      auto_invitation: true,
      phone_attributes: {
        iso: 'PL',
        prefix: '+48',
        number: '777888999'
      }
    }
  end

  it 'service return a created user' do
    expect(subject.instance_of?(User)).to be true
  end

  it 'create a predefined user' do
    expect { subject }.to change(User, :count).by(1)
  end

  it 'create a phone' do
    expect { subject }.to change(Phone, :count).by(1)
  end

  it 'create a predefined participant params' do
    expect { subject }.to change(PredefinedUserParameter, :count).by(1)
  end

  it 'returned user has correct parameters' do
    expect(subject.slice(:first_name, :last_name,
                         :roles).deep_transform_keys!(&:to_s)).to include({ first_name: params[:first_name], last_name: params[:last_name],
                                                                            roles: ['predefined_participant'] })
  end

  it 'has correct email_autogenerated flag' do
    expect(subject.email_autogenerated).to be true
  end

  it 'user has assigned phone' do
    expect(subject.phone).to be_present
  end

  it 'user has predefined user parameter' do
    expect(subject.predefined_user_parameter).to be_present
  end

  it 'predefined user parameters has correct values' do
    expect(subject.predefined_user_parameter.auto_invitation).to be true
  end

  context 'when phone_attributes are skipped' do
    let(:params) do
      {
        first_name: Faker::Name.first_name,
        last_name: Faker::Name.last_name,
        health_clinic_id: health_clinic_id
      }
    end

    it 'doesn\'t create a phone' do
      expect { subject }.not_to change(Phone, :count)
    end
  end

  context 'email has to be uniq' do
    let!(:user) { create(:user, :confirmed) }
    let(:params) do
      {
        first_name: Faker::Name.first_name,
        last_name: Faker::Name.last_name,
        health_clinic_id: health_clinic_id,
        email: user.email
      }
    end

    it 'raise an error' do
      expect { subject }.to raise_exception(ActiveRecord::RecordInvalid)
    end
  end

  describe '.build_predefined_user' do
    subject(:built_user) { described_class.build_predefined_user(build_params) }

    let(:build_params) do
      {
        first_name: 'Alice',
        last_name: 'Smith',
        email: 'alice@example.test'
      }
    end

    it 'returns an unsaved User' do
      expect(built_user).to be_a(User)
      expect(built_user).not_to be_persisted
    end

    it 'does not write to the DB' do
      expect { built_user }.not_to change(User, :count)
    end

    it 'sets the predefined_participant role' do
      expect(built_user.roles).to eq(['predefined_participant'])
    end

    it 'copies first_name, last_name, email from params' do
      expect(built_user.first_name).to eq('Alice')
      expect(built_user.last_name).to eq('Smith')
      expect(built_user.email).to eq('alice@example.test')
    end

    it 'marks email_autogenerated false when email is provided' do
      expect(built_user.email_autogenerated).to be false
    end

    it 'accepts terms' do
      expect(built_user.terms).to be true
    end

    it 'populates a password so Devise validations pass' do
      expect(built_user.password).to be_present
    end

    it 'is valid' do
      expect(built_user).to be_valid
    end

    context 'when email is blank' do
      let(:build_params) do
        {
          first_name: 'Alice',
          last_name: 'Smith'
        }
      end

      it 'autogenerates an email' do
        expect(built_user.email).to match(/\A\d+_[0-9a-f]{20}@predefined-participant\.true\z/)
      end

      it 'marks email_autogenerated true' do
        expect(built_user.email_autogenerated).to be true
      end
    end
  end
end
