# frozen_string_literal: true

RSpec.describe V1::Intervention::PredefinedParticipants::ParticipantAttributesValidator do
  subject(:call) { described_class.call(participant_params_list) }

  let(:health_clinic) { create(:health_clinic) }

  def valid_params(overrides = {})
    ActionController::Parameters.new(
      { first_name: 'Alice', last_name: 'Smith' }.merge(overrides)
    ).permit!
  end

  describe 'happy path' do
    let(:participant_params_list) { [valid_params(email: 'alice@example.test')] }

    it 'returns nil without raising' do
      expect(call).to be_nil
    end

    it 'does not persist any User' do
      expect { call }.not_to change(User, :count)
    end

    it 'does not persist any Phone' do
      expect { call }.not_to change(Phone, :count)
    end

    it 'does not persist any PredefinedUserParameter' do
      expect { call }.not_to change(PredefinedUserParameter, :count)
    end
  end

  describe 'participant with no email (autogenerated branch)' do
    let(:participant_params_list) { [valid_params] }

    it 'passes validation' do
      expect { call }.not_to raise_error
    end
  end

  describe 'intra-CSV duplicate email' do
    let(:participant_params_list) do
      [valid_params(email: 'dup@example.test'), valid_params(email: 'dup@example.test')]
    end

    it 'raises ComplexException with duplicate_in_csv for the second row' do
      expect { call }.to raise_error(ComplexException) do |exc|
        errors = exc.additional_information[:errors]
        duplicate_errors = errors.select { |e| e[:code] == 'duplicate_in_csv' }
        expect(duplicate_errors.size).to eq(1)
        expect(duplicate_errors.first[:row]).to eq(1)
        expect(duplicate_errors.first[:field]).to eq('email')
      end
    end

    it 'does not emit duplicate_in_csv for the first occurrence' do
      expect { call }.to raise_error(ComplexException) do |exc|
        errors = exc.additional_information[:errors]
        row_zero_errors = errors.select { |e| e[:row].zero? && e[:code] == 'duplicate_in_csv' }
        expect(row_zero_errors).to be_empty
      end
    end
  end

  describe 'duplicate email against the DB' do
    let!(:existing) { create(:user, :confirmed) }
    let(:participant_params_list) { [valid_params(email: existing.email)] }

    it 'raises ComplexException with a :taken error code on email' do
      expect { call }.to raise_error(ComplexException) do |exc|
        errors = exc.additional_information[:errors]
        expect(errors).to include(a_hash_including(row: 0, field: 'email', code: 'taken'))
      end
    end
  end

  describe 'invalid email format' do
    let(:participant_params_list) { [valid_params(email: 'not-an-email')] }

    it 'raises ComplexException with at least one error on the email field' do
      # Note: the concrete code string depends on the email validator gem
      # (Devise uses a message string, not a symbol). We pin only the
      # field, not the code, to stay robust across validator-gem changes.
      expect { call }.to raise_error(ComplexException) do |exc|
        email_errors = exc.additional_information[:errors].select { |e| e[:field] == 'email' }
        expect(email_errors).not_to be_empty
      end
    end
  end

  describe 'invalid phone_attributes' do
    let(:participant_params_list) do
      [valid_params(email: 'p@example.test', phone_attributes: { iso: '', prefix: '', number: '' })]
    end

    it 'emits errors with phone.<attr> field prefix' do
      expect { call }.to raise_error(ComplexException) do |exc|
        errors = exc.additional_information[:errors]
        phone_fields = errors.map { |e| e[:field] }.select { |f| f.start_with?('phone.') }
        expect(phone_fields).not_to be_empty
        expect(phone_fields).to all(match(/\Aphone\.(iso|prefix|number)\z/))
      end
    end
  end

  describe 'invalid health_clinic_id (not found)' do
    let(:participant_params_list) do
      [valid_params(email: 'p@example.test', health_clinic_id: SecureRandom.uuid)]
    end

    it 'emits a not_found code on health_clinic_id' do
      expect { call }.to raise_error(ComplexException) do |exc|
        errors = exc.additional_information[:errors]
        expect(errors).to include(a_hash_including(field: 'health_clinic_id', code: 'not_found'))
      end
    end
  end

  describe 'malformed health_clinic_id (frontend contract violation — treated as not_found)' do
    # Should never happen in practice: the frontend's clinic-picker always
    # submits a well-formed UUID from its own dropdown. If one does slip
    # through, Rails silently casts it to no-match and the validator reports
    # `not_found` — UX-equivalent and zero risk of a 500.
    let(:participant_params_list) do
      [valid_params(email: 'p@example.test', health_clinic_id: 'not-a-uuid')]
    end

    it 'emits a not_found code (no 500, no special invalid_uuid handling)' do
      expect { call }.to raise_error(ComplexException) do |exc|
        errors = exc.additional_information[:errors]
        expect(errors).to include(a_hash_including(field: 'health_clinic_id', code: 'not_found'))
      end
    end
  end

  describe 'valid health_clinic_id' do
    let(:participant_params_list) do
      [valid_params(email: 'p@example.test', health_clinic_id: health_clinic.id)]
    end

    it 'passes validation' do
      expect { call }.not_to raise_error
    end
  end

  describe 'empty participants list' do
    let(:participant_params_list) { [] }

    it 'returns nil without raising' do
      expect(call).to be_nil
    end
  end

  describe 'HIPAA — no PII values in error payloads' do
    let(:email) { 'leaktest@example.test' }
    let!(:existing) { create(:user, :confirmed, email: email) }
    let(:participant_params_list) do
      [valid_params(email: email, health_clinic_id: 'not-a-uuid', phone_attributes: { iso: '', prefix: '', number: '' })]
    end

    it 'no error entry contains the email, name, or malformed UUID value' do
      expect { call }.to raise_error(ComplexException) do |exc|
        serialised = exc.additional_information[:errors].to_s
        expect(serialised).not_to include(email)
        expect(serialised).not_to include('Alice')
        expect(serialised).not_to include('Smith')
        expect(serialised).not_to include('not-a-uuid')
      end
    end

    it 'ComplexException.message does not contain PII' do
      expect { call }.to raise_error(ComplexException) do |exc|
        expect(exc.message).not_to include(email)
      end
    end
  end

  describe 'error entry shape' do
    let!(:existing) { create(:user, :confirmed) }
    let(:participant_params_list) { [valid_params(email: existing.email)] }

    it 'every entry has :row, :field, :code keys' do
      expect { call }.to raise_error(ComplexException) do |exc|
        exc.additional_information[:errors].each do |entry|
          expect(entry).to include(:row, :field, :code)
          expect(entry[:row]).to be_a(Integer)
          expect(entry[:field]).to be_a(String)
          expect(entry[:code]).to be_a(String)
        end
      end
    end
  end
end
