default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 4 } %>
  encoding: unicode

development:
  <<: *default
  database: cias_development

test:
  <<: *default
  database: cias_test

production:
  <<: *default
  database: cias_production
  username: <%= ENV['CIAS_DATABASE_USER'] %>
  password: <%= ENV['CIAS_DATABASE_PASSWORD'] %>
