default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 4 } %>
  encoding: unicode

development:
  <<: *default
  database: cias_development

test:
  <<: *default
  database: cias_test
