development:
  adapter: postgresql
  host: database
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 4 } %>
  encoding: unicode
  database: cias_development
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
