default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: cias_development

test:
  <<: *default
  database: cias_test

production:
  <<: *default
  database: cias_production
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
