default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 4 } %>
  encoding: unicode

development:
  <<: *default
  database: cias_development

test:
  <<: *default
  database: cias_test

non_production:
  <<: *default
  database: cias_non_production
  host: <%= ENV['CIAS_NONPROD_DATABASE_HOST'] %>
  username: <%= ENV['CIAS_NONPROD_DATABASE_USER'] %>
  password: <%= ENV['CIAS_NONPROD_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: cias_production
  host: <%= ENV['CIAS_DATABASE_HOST'] %>
  username: <%= ENV['CIAS_DATABASE_USER'] %>
  password: <%= ENV['CIAS_DATABASE_PASSWORD'] %>
