---
:concurrency: <%= ENV.fetch('RAILS_MAX_THREADS') { 4 } %>
:queues:
  - [default,4]
  - [reports,5]
  - [sms_plans, 5]
  - [question_sms, 5]
  - [mailers,5]
  - [log,1]
  - [active_storage_purge,1]
  - [active_storage_analysis,1]
  - [clone,4]
  - [translations,4]
  - [session_finish,4]
  - [hfhs,4]
