name: Continuous integration
on: push

jobs:
  build:
    parallelism: 4
    docker:
      - image: ruby:2.7.1
        name: api
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
          GIT_AUTHOR_EMAIL: ci@ci.ci
          POSTGRES_PASSWORD: 'Z9iiJQKeSxz'
          RAILS_ENV: test
      - image: postgres:13
        name: database
        environment:
          POSTGRES_PASSWORD: 'Z9iiJQKeSxz'
      - image: redis:6.0.5
        name: cache
    steps:
      - checkout
      - run:
          command: cp .env.template .env
      - restore_cache:
          keys:
            - cias-api-bundle-v2-{{ checksum "Gemfile.lock" }}
            - cias-api-bundle-v2-
      - run:
          name: Install gems
          command: |
            gem install bundler -v "2.1.4"
            bundle install -j4 --path vendor/bundle
      - save_cache:
          key: cias-api-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          command: bundle exec overcommit -i && bundle exec overcommit --sign pre-commit
      - run:
          name: Overcommit feedback
          command: bundle exec overcommit -r
      - run:
          name: Database setup
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: Execute tests
          command: |
            mkdir /tmp/test-results
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec rspec $TESTFILES --out /tmp/test-results/rspec.xml --format progress
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
