# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.1'

gem 'middleman', '~>4.3'
gem 'middleman-syntax', '~> 3.0'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-sprockets', '~> 4.1'
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'
gem 'nokogiri', '~> 1.10.4'
gem 'sass'
gem 'dotenv'
